security:
    encoders: #defini le type d'encodage
         App\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity: # permet de dire a symfnony que quand il y a un log, c'est le username de User qu'il faut utiliser
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                invalidate_session: true
                path: /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

