<?php

namespace App\Controller;

use App\Form\ProduitInternType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use App\Entity\ProduitIntern;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class ProduitInternController extends Controller
{
    /**
     * @Route("/addteeintern", name="add_tee_intern")
     */
    public function addAction(Request $request)
    {
        $tee =  new ProduitIntern();
        $form = $this->createForm(ProduitInternType::class, $tee);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()){
            if ($form->isSubmitted() && $form->isValid()){
                $em = $this->getDoctrine()->getManager();
                $em->persist($tee);
                $em->flush();
                $request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée.');
                return $this->redirectToRoute('add_tee_intern');

            }
        }

        return $this->render('addTeeIntern.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
