easy_admin:
    site_name: 'NiceTee Admin'
    entities:
        - App\Entity\Commande
        - App\Entity\ProduitIntern
        - App\Entity\ProduitMembre
        - App\Entity\User
        - App\Entity\Image
        - App\Entity\DeliveryAdressUser
framework:
    translator: { fallbacks: [ "fr" ] }