easy_admin:
    design:
        menu:
            - label: 'Manager'
            - label: 'Tee Intern'
              children:
                  - { entity: 'LeBoTee', label: 'LeBo Tee', default: true}
                  - { entity: 'TeeAuthentica', label: 'Tee Authentica'}
                  - { entity: 'CoffeCentral', label: 'Coffe Central'}
            - label: 'Tee Membres'
              children:
                  - { entity: 'ProduitsMembres', label: 'Tee Membres'}
            - label: 'Membres'
              children:
                  - { entity: 'Membres', label: 'Membres'}
            - label: 'Gestion des Commande'
              children:
                  - { entity: 'CommandeATraiter', label: 'Commande à traiter'}
                  - { entity: 'CommandeTraite', label: 'Commande traité'}
            - label: 'Env: %env(APP_ENV)%'