easy_admin:
        entities:
            Membres:
                class: App\Entity\User
                controller: App\Controller\AdminUserController
                form:
                    fields:
                        - "id"
                        - {property: 'username'}
                        - {property: 'dateInscription', format: 'd/m/Y'}
                        - {property: 'nom'}
                        - {property: 'prenom'}
                        - {property: 'sex'}
                        - {property: 'phoneNumber'}
                        - {property: 'adresse'}
                        - {property: 'codePostal'}
                        - {property: 'ville'}
                        - {property: 'pays'}
                        - {property: 'email'}
                list:
                    fields:
                        - "id"
                        - {property: 'username'}
                        - {property: 'dateInscription', format: 'd/m/Y'}
                        - {property: 'nom'}
                        - {property: 'prenom'}
                        - {property: 'sex'}
                        - {property: 'email'}
                        - {property: 'phoneNumber'}
                        - {property: 'adresse'}
                        - {property: 'codePostal'}
                        - {property: 'ville'}
                        - {property: 'pays'}
                        - {property: 'roles'}

